name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean verify

  check-tag:
    name: Ensure a release tag exists
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check for tag on PR branch
        run: |
          echo "HEAD_REF=${{ github.event.pull_request.head.ref }}"
          git fetch --tags
          TAG_COUNT=$(git tag --points-at HEAD | wc -l)
          echo "Number of tags on this commit: $TAG_COUNT"
          if [ "$TAG_COUNT" -eq "0" ]; then
            echo "::error::A Git tag (release version) must be created before merging to main."
            exit 1
          fi
